a = input('Digite algo: ')
print('O tipo primitivo desse valor é:' ,type(a))
print(f'É numérico? {a.isnumeric()}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isnumeric()}')
print(f'Está em maiúsulas? {a.isupper()}')
print(f'Está em minúsulas? {a.islower()}')
print(f'Está em capitalizada? {a.istitle()}')
