a = input('Digite algo: ')
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('É numérico? ', a.isnumeric())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())
