nome = str(input('Digite o seu nome completo: ')).strip()
print('Analisando o seu nome...')
print(f'Seu nome em maíusculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
espaços = nome.count(' ')
print(f'A quantidade de letras é {len(nome) - espaços}')
encotrar = nome.find(' ')
separa = nome.split()
print(f'Seu primeiro nome tem {len(separa[0])} letras')
#print(f'Seu primeiro nome tem {encotrar} letras')